repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.5.0
    hooks:
      - id: check-ast
      - id: check-merge-conflict
        exclude: '\.rst$'

      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-docstring-first
      - id: mixed-line-ending
        args: [--fix=lf]
      - id: check-json
      # check for file bigger than 500kb
      - id: check-added-large-files
      - id: check-yaml
      - id: debug-statements
      - id: fix-encoding-pragma
        args: [--remove]

  - repo: https://github.com/Trim21/find-trailing-comma
    rev: v0.0.1
    hooks:
      - id: find-trailing-comma

  - repo: https://github.com/asottile/pyupgrade
    rev: v2.1.1
    hooks:
      - id: pyupgrade
        args: ["--py36-plus"]

  - repo: https://github.com/PyCQA/doc8
    rev: 0.8.1rc3 # versioning=pep440
    hooks:
      - id: doc8
        args: ["--max-line-length", "88", "-v"]
        files: \.rst$
        exclude: '.*/_autoapi/.*\.rst$'

  - repo: https://github.com/Trim21/mirrors-autoflake
    rev: v1.3.1
    hooks:
      - id: autoflake
        require_serial: true
        args:
          [
            "--in-place",
            "--remove-unused-variables",
            "--remove-all-unused-imports",
            "--expand-star-imports",
          ]

  - repo: https://github.com/timothycrosley/isort
    rev: 4.3.21-2
    hooks:
      - id: isort
        require_serial: true
        args:
          [
            "--line-width=88",
            "--trailing-comma",
            "--multi-line=3",
            "--project=bgmi",
            "--section-default=THIRDPARTY",
          ]

  - repo: https://github.com/Trim21/poetry-check-lock
    rev: v0.0.2
    hooks:
      - id: poetry-check-lock
        additional_dependencies:
          # renovate: pypi versioning=pep440
          - poetry==1.0.5

  - repo: https://github.com/PyCQA/flake8
    rev: 3.8.1
    hooks:
      - id: flake8
        additional_dependencies:
          # renovate: pypi versioning=pep440
          - flake8-commas==2.0.0
          # renovate: pypi versioning=pep440
          - flake8-comprehensions==3.2.2
          # renovate: pypi versioning=pep440
          - flake8-mutable==1.2.0

  - repo: local
    hooks:
      - id: blacken-docs
        name: blacken-docs
        description: Run `black` on python code blocks in documentation files
        entry: blacken-docs
        language: system
        files: '\.(rst|md|markdown|py|tex)$'

      - id: black
        name: black
        entry: black
        require_serial: true
        language: system
        types: [python]

      - id: mypy
        name: mypy
        entry: mypy
        language: system
        types: [python]
        args: ["--ignore-missing-imports"]
        require_serial: true
        exclude: '^.*[\\/](test_[^\\/]*)\.py$' # exclude file name starts with 'test_'
