[tool.poetry]
name = "bgmi"
version = "3.0.0a0"
description = "BGmi is a cli tool for subscribed bangumi."
keywords=['bangumi', 'bgmi', 'feed']
authors = [
    "RicterZ <ricterzheng@gmail.com>",
    "Trim21 <i@trim21.me>"
]
readme = 'readme.md'
license = "MIT"
repository = 'https://github.com/BGmi/BGmi'
homepage = 'https://github.com/BGmi/BGmi'
classifiers = [
  'Development Status :: 4 - Beta',
  'Intended Audience :: Other Audience',
  'Natural Language :: Chinese (Traditional)',
  'License :: OSI Approved :: MIT License',
  'Programming Language :: Python',
  'Programming Language :: Python :: 3',
  'Programming Language :: Python :: 3.6',
  'Programming Language :: Python :: 3.7',
  'Programming Language :: Python :: 3.8',
  'Programming Language :: Python :: Implementation :: CPython',
]

include = ["LICENSE", "readme.md"]
packages = [
    { include = "bgmi" },
]

[tool.poetry.dependencies]
python = "^3.6"

stevedore = "1.32.0"


[tool.poetry.dev-dependencies]
autoflake = "1.3.1"
mypy = '0.750'
pre-commit = "2.1.0"
isort = "4.3.21"
black = '19.10b0'

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
